version: '3.0'
services:
  web:
    image: web-app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
